### PR TITLE
To markdown 1.2.0

### LINKED ISSUE #2: Uncaught ReferenceError: merge is not defined
Using the standalone version i get "Uncaught ReferenceError: merge is not defined" when running the script. It looks like it's the code from he.js that hasn't been properly included.

On this line merge is called in the standalone file, but it's not defined anywhere inside that file:
https://github.com/IonicaBizau/medium-editor-markdown/blob/master/dist/me-markdown.standalone.js#L7

Here merge is defined in he.js:
https://github.com/mathiasbynens/he/blob/master/src/he.js#L89

### LINKED ISSUE #4: Create lists
How is it possible to start a list?

Trying to create one on the demo site:
http://ionicabizau.github.io/medium-editor-markdown/

I would expect that beginning a line with '*' would work, but it doesn't.

### PR DESCRIPTION
**Pull request by IonicaBizau**
- :arrow_up: Upgraded to `to-markdown@1.2.0`
- :fire: Removed the `he` dependency.
- Fixes several conversion issues (after upgrading the `to-markdown` version). Fixes #4.
- Fixes #2. Since we don't need `he` anymore, issues related to the private functions are gone.

### CODE REVIEW

**Comment by IonicaBizau** [comment]
:fireworks: :ship: Released `1.2.0` :tada:

**Comment by thomasjthomasj** [comment]
Hi @IonicaBizau, we were getting the same issue as @axelson and found that it occurred when backticks/`code` tags were used in the markdown. I've just installed this most recent update and it looks like it's fixed it. I'll let you know if I see any signs of it again. Thanks!

**Comment by IonicaBizau** [comment]
@thomasjthomasj Glad to hear that! :smile:

**Pull request merged**
