### PR TITLE
Init function update for 5.8.2

### PR DESCRIPTION
**Pull request by prevuelta**
Fix to work with latest version of medium-editor (5.8.2)

### CODE REVIEW

**Comment by IonicaBizau** [comment]
Oh, cool! Can you please update the medium editor version too, in example?

**Comment by prevuelta** [comment]
No probs, will have a proper look at it soon

**Comment by dmshvetsov** [comment]
Ping. This PR will be integrated into the master?

**Comment by IonicaBizau** [comment]
@shvetsovdm Of course, but @prevuelta should update the Medium Editor version as well! Also, the examples should be updated.  :dizzy: 

I cannot wait to merge this! :smile:

**Comment by dmshvetsov** [comment]
@IonicaBizau I understand, thanks.

**Pull request closed without merging**
