### PR TITLE
Changed to-markdown depedency to turndown

### PR DESCRIPTION
**Pull request by sunilhari**
The to-markdown dependency had been modified and had changed to turndown with slight modifications in its usage.This PR incorporates those changes

### CODE REVIEW

**Review by IonicaBizau — CHANGES_REQUESTED** [review]
This is amazing! :sparkles: 

Can you please rename `toTurnDownOptions` into `toTurndownOptions` and `ignorebuiltinconverters` into `ignoreBuiltinConverters`?

I think it would look better.

Thanks!

**Comment by sunilhari** [comment]
Ya would get on it rightaway.

**Comment by sunilhari** [comment]
@IonicaBizau  Have made the change.

**Review by IonicaBizau — APPROVED** [review]

**Comment by sunilhari** [comment]
@IonicaBizau .Will it be merged.When is the next release ?

**Comment by IonicaBizau** [comment]
I'm on it. 5 min

**Comment by IonicaBizau** [comment]
:ship: **`3.0.0`** :tada:

**Comment by sunilhari** [comment]
Thank you.Deleting the branch  @IonicaBizau

**Pull request merged**
